// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1K1Mu8MJdTohr9cG8qPdEH2I1uqUBu3c',
    appId: '1:708857098134:web:db3aaf099888f0df9377b7',
    messagingSenderId: '708857098134',
    projectId: 'diyah-app',
    authDomain: 'diyah-app.firebaseapp.com',
    storageBucket: 'diyah-app.firebasestorage.app',
    measurementId: 'G-QBGKF7ERWB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMnshnv3hIfcyJ4IvSy7TK-z7176hsmZk',
    appId: '1:708857098134:android:35b7a174faf6e25b9377b7',
    messagingSenderId: '708857098134',
    projectId: 'diyah-app',
    storageBucket: 'diyah-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnE1KLqDXYCF4NPuQ-Y_OS-7IiTil5uEU',
    appId: '1:708857098134:ios:a2fe90476c9329c89377b7',
    messagingSenderId: '708857098134',
    projectId: 'diyah-app',
    storageBucket: 'diyah-app.firebasestorage.app',
    iosBundleId: 'com.abuhamdan.tribalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnE1KLqDXYCF4NPuQ-Y_OS-7IiTil5uEU',
    appId: '1:708857098134:ios:a2fe90476c9329c89377b7',
    messagingSenderId: '708857098134',
    projectId: 'diyah-app',
    storageBucket: 'diyah-app.firebasestorage.app',
    iosBundleId: 'com.abuhamdan.tribalApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1K1Mu8MJdTohr9cG8qPdEH2I1uqUBu3c',
    appId: '1:708857098134:web:54c8eb59536cae399377b7',
    messagingSenderId: '708857098134',
    projectId: 'diyah-app',
    authDomain: 'diyah-app.firebaseapp.com',
    storageBucket: 'diyah-app.firebasestorage.app',
    measurementId: 'G-LTT30V7XYK',
  );
}
